from typing import Any, Iterable, Sequence

class InterpolationMode:
    BICUBIC: Any

class Compose:
    def __init__(self, transforms: Sequence[Any]) -> None: ...
    def __call__(self, image: Any) -> Any: ...

class Resize:
    def __init__(self, size: int | tuple[int, int], interpolation: Any | None = ...) -> None: ...
    def __call__(self, image: Any) -> Any: ...

class RandomAffine:
    def __init__(
        self,
        degrees: float | tuple[float, float],
        translate: tuple[float, float] | None = ...,
        scale: tuple[float, float] | None = ...,
        shear: float | tuple[float, float] | None = ...,
        interpolation: Any | None = ...,
    ) -> None: ...
    def __call__(self, image: Any) -> Any: ...

class ColorJitter:
    def __init__(
        self,
        brightness: float | tuple[float, float] = ...,
        contrast: float | tuple[float, float] = ...,
        saturation: float | tuple[float, float] = ...,
        hue: float | tuple[float, float] = ...,
    ) -> None: ...
    def __call__(self, image: Any) -> Any: ...

class ToTensor:
    def __init__(self) -> None: ...
    def __call__(self, image: Any) -> Any: ...

class Normalize:
    def __init__(self, mean: Iterable[float], std: Iterable[float], inplace: bool = ...) -> None: ...
    def __call__(self, tensor: Any) -> Any: ...

class RandomErasing:
    def __init__(
        self,
        p: float = ...,
        scale: tuple[float, float] = ...,
        ratio: tuple[float, float] = ...,
        value: int | float | str | Sequence[float] = ...,
        inplace: bool = ...,
    ) -> None: ...
    def __call__(self, tensor: Any) -> Any: ...

class RandomAutocontrast:
    def __init__(self, p: float = ...) -> None: ...
    def __call__(self, image: Any) -> Any: ...

class RandomAdjustSharpness:
    def __init__(self, sharpness_factor: float, p: float = ...) -> None: ...
    def __call__(self, image: Any) -> Any: ...

class RandomApply:
    def __init__(self, transforms: Sequence[Any], p: float = ...) -> None: ...
    def __call__(self, image: Any) -> Any: ...

class GaussianBlur:
    def __init__(self, kernel_size: int | Sequence[int], sigma: float | tuple[float, float] = ...) -> None: ...
    def __call__(self, image: Any) -> Any: ...

