from typing import Any


def create_model(model_name: str, pretrained: bool = ..., num_classes: int = ..., **kwargs: Any) -> Any: ...
def list_models(*, pretrained: bool = ..., **kwargs: Any) -> list[str]: ...
