from typing import Any

class MapieRegressor:
    def __init__(self, estimator: Any = ..., method: str = ..., cv: int = ...) -> None: ...
    def fit(self, X: Any, y: Any) -> MapieRegressor: ...
    def predict(self, X: Any, alpha: float = ...) -> tuple[Any, Any]: ...

