from typing import Any, Sequence

class _Node:
    name: str

class InferenceSession:
    def __init__(self, path_or_bytes: str | bytes, providers: Sequence[str] | None = ...) -> None: ...
    def get_inputs(self) -> list[_Node]: ...
    def get_outputs(self) -> list[_Node]: ...
    def run(self, output_names: Sequence[str] | None, input_feed: dict[str, Any]) -> list[Any]: ...

