from typing import Any


class ExtraTreesClassifier:
    def __init__(self, **kwargs: Any) -> None: ...
    def fit(self, X: Any, y: Any) -> ExtraTreesClassifier: ...
    def predict_proba(self, X: Any) -> Any: ...


class HistGradientBoostingClassifier:
    def __init__(self, **kwargs: Any) -> None: ...
    def fit(self, X: Any, y: Any) -> HistGradientBoostingClassifier: ...
    def predict_proba(self, X: Any) -> Any: ...
