from typing import Any

class Ridge:
    def __init__(self, alpha: float = ..., **kwargs: Any) -> None: ...
    def fit(self, X: Any, y: Any) -> Ridge: ...
    def predict(self, X: Any) -> Any: ...

class LogisticRegression:
    def __init__(
        self,
        *,
        C: float = ...,
        class_weight: str | dict[object, float] | None = ...,
        max_iter: int = ...,
        random_state: int | None = ...,
        **kwargs: Any,
    ) -> None: ...
    def fit(self, X: Any, y: Any) -> LogisticRegression: ...
    def predict_proba(self, X: Any) -> Any: ...
